### ISSUE TITLE
Create a login Page

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/Lost-And-Found-Mobile-App#1]
A login Page for user with an aethetic appeal. Refer to the designs below for inspiration:-
<img width="144" alt="image" src="https://github.com/upes-open/Lost-And-Found-Mobile-App/assets/103314396/44380905-ac80-49b2-b9c8-f297a68ee8e9">

Make sure you only add the sign in button and some image if you want, refer to the webapp for further clarification.

**Comment by ThapaVinay** [comment]
i want to work on this

**Comment by ThapaVinay** [comment]
i want to work on this

**Comment by aakshitaa** [comment]
> i want to work on this

Sure

**Comment by aakshitaa** [comment]
issue is completed by @ThapaVinay
