### ISSUE TITLE
Create a help us find page

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/Lost-And-Found-Mobile-App#10]
![image](https://github.com/upes-open/Lost-And-Found-Mobile-App/assets/103314396/6c7340b8-4f7f-425e-b407-2ce7987f0873)
Instead of scrolling from top to bottm , for the help us find page we shall scroll from left to right and display the items that are lost and should be reported if found.

**Comment by ThapaVinay** [comment]
i want to work on this

**Comment by aakshitaa** [comment]
> i want to work on this

sure

**Comment by aakshitaa** [comment]
This issue was completed by @ThapaVinay
