### ISSUE TITLE
Items Gallery Page- Show items based on category 

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/Lost-And-Found-Mobile-App#13]
This page will display items based on the selected category. You may refer to the images below to get an idea of how the page is expeted to look:
<img width="151" alt="image" src="https://github.com/upes-open/Lost-And-Found-Mobile-App/assets/103314396/60be1135-5d3b-4610-bae0-f80eead5efd7">
In place of circlles in bottom right, there will be a "See Details" button

**Comment by akssshh** [comment]
Hey @aakshitaa Can i work on you assign this to me?

**Comment by aakshitaa** [comment]
> Hey @aakshitaa Can i work on you assign this to me?

Sure

**Comment by ArshdeepKaur04** [comment]
I want to work on this issue
