### ISSUE TITLE
Items Gallery Page- Details about the item

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/Lost-And-Found-Mobile-App#14]
When the user click on see details button from #13 then they will be directed to this page. Here they will know about the details about the item, which are collected from #5 
Refer to below image for idea about the design:
<img width="247" alt="image" src="https://github.com/upes-open/Lost-And-Found-Mobile-App/assets/103314396/7c3ad782-eabf-4098-9918-b502b7ef5ded">
**Instead of Add to  cart there will be a "Claim" button**

**Comment by Thilagavathi1** [comment]
@aakshitaa i would like to work on this issue.Could u please assign this issue to me
