### ISSUE TITLE
Items Gallery Page- Claim item form

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/Lost-And-Found-Mobile-App#15]
This form will contain the following details-
<img width="302" alt="image" src="https://github.com/upes-open/Lost-And-Found-Mobile-App/assets/103314396/ca7b63f1-e31a-4dff-97ba-ec052e994a1b">
All the details will be mandatory.

**Comment by Chetax** [comment]
What Has To Be Done In this Issue

**Comment by aakshitaa** [comment]
> What Has To Be Done In this Issue

You have to create a similar form for the app, that's all, just make sure that when you do so you keep the folder structure in mind, which will be- create a new folder for items gallery page (if not already made), then create the jsx file there with name detailsform or just form

**Comment by aakshitaa** [comment]
@Chetax you may join our discord channel if you want https://discord.gg/bx3rbcZZ

**Comment by Chetax** [comment]
@aakshitaa i would like to work on this issue can you please assign it to me

**Comment by ThapaVinay** [comment]
i want to work on this

**Comment by aakshitaa** [comment]
@Chetax This issue was completed by @ThapaVinay , you may continue working on some other issues
