### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/Lost-And-Found-Mobile-App#17]
Create a basic profile page for the user which will have an option of logging out, and will display the number of  items reported as lost or found .
<img width="111" alt="image" src="https://github.com/upes-open/Lost-And-Found-Mobile-App/assets/103314396/5e92a48c-e8a0-4a11-b30d-70efcefaa664">

**Comment by rampantvoid** [comment]
Hey, I would like to work on this issue. Can you please assign it to me?

**Comment by aakshitaa** [comment]
> Hey, I would like to work on this issue. Can you please assign it to me?

Assigned!

**Comment by rishabh-108272** [comment]
I want to work on this issue.

**Comment by aakshitaa** [comment]
@rampantvoid can you share the sccreenshots of the profile page here

**Comment by rampantvoid** [comment]
> @rampantvoid can you share the sccreenshots of the profile page here

![Screenshot_20231030-230307](https://github.com/upes-open/Lost-And-Found-Mobile-App/assets/59150296/779c8b3f-7090-482f-8c01-6d696ff76bd2)

**Comment by aakshitaa** [comment]
@rampantvoid thanks
