### ISSUE TITLE
Create a basic landing page/ Home Page

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/Lost-And-Found-Mobile-App#2]
This page will be the first page  the  user will get once they succesfully sign in. 
<img width="115" alt="image" src="https://github.com/upes-open/Lost-And-Found-Mobile-App/assets/103314396/34004566-6117-4863-b174-cd36c9980053">
<img width="114" alt="image" src="https://github.com/upes-open/Lost-And-Found-Mobile-App/assets/103314396/60cbbf7f-fe09-4002-9f7b-137205e39f12">
<img width="168" alt="image" src="https://github.com/upes-open/Lost-And-Found-Mobile-App/assets/103314396/3dbd873f-7864-465d-9e7f-24856483b263">

This page will basically point to the other pages which are useful. It will point to- Report Lost Item, Report Found Item, Items Gallery, Help Us Find, Feedback and FAQ

**Comment by ArshdeepKaur04** [comment]
I want to work on this issue

**Comment by aakshitaa** [comment]
> I want to work on this issue

Assigned

**Comment by ThapaVinay** [comment]
i want to work on this under hacktoberfest.
