### ISSUE TITLE
Integration with cloudinary

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/Lost-And-Found-Mobile-App#21]
The backend is built using MongoDB. We need to upload images on it but we can't store that much data on MongoDB hence we need to connect it Cloudinary which will store our images. 
You may ask for the MongoDB credentials

**Comment by thezeeshann** [comment]
@aakshitaa can you assign me this issue

**Comment by aakshitaa** [comment]
> @aakshitaa can you assign me this issue

Assigned

**Comment by thezeeshann** [comment]
@aakshitaa This is a native app. Sorry I haven't experienced a native app.

**Comment by aakshitaa** [comment]
> @aakshitaa This is a native app. Sorry I haven't experienced a native app.

so you want to quit this issue ?

**Comment by thezeeshann** [comment]
@aakshitaa yeah pls. give the another person

**Comment by Manav-Khandurie** [comment]
If this issue is avaliable you can assign it to me

**Comment by aakshitaa** [comment]
> If this issue is avaliable you can assign it to me

Sure

**Comment by Manav-Khandurie** [comment]
I Have raised a PR for the Same
