### ISSUE TITLE
Create FAQ Page

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/Lost-And-Found-Mobile-App#23]
For FAQ content, refer to the web app: https://osoc-lost-and-found-webapp.netlify.app/
Sample Ideas for FAQ Page
<img width="127" alt="image" src="https://github.com/upes-open/Lost-And-Found-Mobile-App/assets/103314396/240612f8-bbaa-4848-958e-9397d3a41f63">
<img width="122" alt="image" src="https://github.com/upes-open/Lost-And-Found-Mobile-App/assets/103314396/a6dfc508-0416-437d-94fc-41b0fae8236a">

**Comment by mustafaazad03** [comment]
Hi, I find this issue interesting. can I work on this ??

**Comment by aakshitaa** [comment]
> Hi, I find this issue interesting. can I work on this ??

Sure

**Comment by ArshdeepKaur04** [comment]
I want to work on this issue

**Comment by mustafaazad03** [comment]
Pls check my PR.

**Comment by mustafaazad03** [comment]
Please Add hacktoberfest accepted label so that this PR will be accepted for hacktoberfest
![image](https://github.com/upes-open/Lost-And-Found-Mobile-App/assets/97380192/6217e8df-ae4c-4010-8981-25260809022f)
