### ISSUE TITLE
Refine the drawer menu

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/Lost-And-Found-Mobile-App#24]
The drawer style menu is created but it is  not aesthetically pleasing. Transform the content in chronological order and add relatable icons for each item.

**Comment by Thilagavathi1** [comment]
@aakshitaa Could u please assign this issue to me ?

**Comment by Thilagavathi1** [comment]
@aakshitaa raised an[ PR](https://github.com/upes-open/Lost-And-Found-Mobile-App/pull/26).Please review this.

**Comment by Thilagavathi1** [comment]
Hi @aakshitaa 
let me know if any issues on the [PR](https://github.com/upes-open/Lost-And-Found-Mobile-App/pull/26)
