### ISSUE TITLE
Storing user data  in the database with node

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/Lost-And-Found-Mobile-App#25]
Currently the user's data is not stored in the database. Store the data of each user logging in. Use the existing MongoDB database and nodejs for connectivity.

**Comment by subhashree9898** [comment]
@aakshitaa please assign this issue to me.

**Comment by sujithyadav998** [comment]
I am interested in working on this. @aakshitaa can you assign me this?

**Comment by aakshitaa** [comment]
Sure @sujithyadav998 @subhashree9898

**Comment by Vaibhav-Rawat03** [comment]
Assign this issue to me

**Comment by rampantvoid** [comment]
@aakshitaa can you assign this issue to me?

**Comment by aakshitaa** [comment]
> @aakshitaa can you assign this issue to me?

sure

**Comment by rampantvoid** [comment]
> > @aakshitaa can you assign this issue to me?
> 
> sure

can you provide me with access to the production DB

**Comment by rampantvoid** [comment]
@aakshitaa also i having trouble while trying out the login functionality ig the inbound requests are restricted
![Screenshot_20231030-233747](https://github.com/upes-open/Lost-And-Found-Mobile-App/assets/59150296/8195d761-b5e8-44b0-9481-c7f9a3668b49)

**Comment by aakshitaa** [comment]
> > > @aakshitaa can you assign this issue to me?
> > 
> > 
> > sure
> 
> can you provide me with access to the production DB

Drop your mail I'll send invite for atlas

**Comment by aakshitaa** [comment]
> @aakshitaa also i having trouble while trying out the login functionality ig the inbound requests are restricted ![Screenshot_20231030-233747](https://user-images.githubusercontent.com/59150296/279155021-8195d761-b5e8-44b0-9481-c7f9a3668b49.jpg)

Yes actually the login page is not working properly, and we are using msal, if you can fix it then you can assign the issue and work on it first because with that working, it will be difficult to work on user data collection.

**Comment by rampantvoid** [comment]
> > > @aakshitaa can you assign this issue to me?
> > 
> > 
> > sure
> 
> can you provide me with access to the production DB

priyanshubutola@gmail.com

**Comment by rampantvoid** [comment]
> > @aakshitaa also i having trouble while trying out the login functionality ig the inbound requests are restricted ![Screenshot_20231030-233747](https://user-images.githubusercontent.com/59150296/279155021-8195d761-b5e8-44b0-9481-c7f9a3668b49.jpg)
> 
> Yes actually the login page is not working properly, and we are using msal, if you can fix it then you can assign the issue and work on it first because with that working, it will be difficult to work on user data collection.

yeah sure but i don't see any issue raised specific to this problem

**Comment by aakshitaa** [comment]
> > > > @aakshitaa can you assign this issue to me?
> > > 
> > > 
> > > sure
> > 
> > 
> > can you provide me with access to the production DB
> 
> [priyanshubutola@gmail.com](mailto:priyanshubutola@gmail.com)

Sent you the invite

**Comment by aakshitaa** [comment]
> > > @aakshitaa also i having trouble while trying out the login functionality ig the inbound requests are restricted ![Screenshot_20231030-233747](https://user-images.githubusercontent.com/59150296/279155021-8195d761-b5e8-44b0-9481-c7f9a3668b49.jpg)
> > 
> > 
> > Yes actually the login page is not working properly, and we are using msal, if you can fix it then you can assign the issue and work on it first because with that working, it will be difficult to work on user data collection.
> 
> yeah sure but i don't see any issue raised specific to this problem

Yes it is now fixed, you may check on your end

**Comment by rampantvoid** [comment]
@aakshitaa i'm not able to access the collection ig i need additional access

**Comment by rampantvoid** [comment]
> > > > @aakshitaa also i having trouble while trying out the login functionality ig the inbound requests are restricted ![Screenshot_20231030-233747](https://user-images.githubusercontent.com/59150296/279155021-8195d761-b5e8-44b0-9481-c7f9a3668b49.jpg)
> > > 
> > > 
> > > Yes actually the login page is not working properly, and we are using msal, if you can fix it then you can assign the issue and work on it first because with that working, it will be difficult to work on user data collection.
> > 
> > 
> > yeah sure but i don't see any issue raised specific to this problem
> 
> Yes it is now fixed, you may check on your end

still facing the same issue

**Comment by aakshitaa** [comment]
> @aakshitaa i'm not able to access the collection ig i need additional access

sent another invite.. try now

**Comment by aakshitaa** [comment]
> > > > > @aakshitaa also i having trouble while trying out the login functionality ig the inbound requests are restricted ![Screenshot_20231030-233747](https://user-images.githubusercontent.com/59150296/279155021-8195d761-b5e8-44b0-9481-c7f9a3668b49.jpg)
> > > > 
> > > > 
> > > > Yes actually the login page is not working properly, and we are using msal, if you can fix it then you can assign the issue and work on it first because with that working, it will be difficult to work on user data collection.
> > > 
> > > 
> > > yeah sure but i don't see any issue raised specific to this problem
> > 
> > 
> > Yes it is now fixed, you may check on your end
> 
> still facing the same issue

can you join our discord channel https://discord.gg/mdvnDJMf.. select role as collaboration vertical and you can see the project - lost and found app in the channel list. Will be easier to contact with you there
