### ISSUE TITLE
Create Report Lost Item Page

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/Lost-And-Found-Mobile-App#3]
This page will basically be a form and will be used to fetch user data. Refer to the webapp for the feilds to be included. 
<img width="176" alt="image" src="https://github.com/upes-open/Lost-And-Found-Mobile-App/assets/103314396/b89c09b2-404c-434f-9f0c-6bbd9d4af9d2">
<img width="597" alt="image" src="https://github.com/upes-open/Lost-And-Found-Mobile-App/assets/103314396/426141de-f018-444c-8412-6f2c4cac74e8">

**Comment by helloakash1701** [comment]
I would like to work upon this issue

**Comment by aakshitaa** [comment]
> I would like to work upon this issue

Assigned

**Comment by ThapaVinay** [comment]
i want to work on this

**Comment by aakshitaa** [comment]
> i want to work on this

Assigned
