### ISSUE TITLE
create a feedback page

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/Lost-And-Found-Mobile-App#6]
<img width="421" alt="image" src="https://github.com/upes-open/Lost-And-Found-Mobile-App/assets/103314396/b2cb4a78-404c-4d0e-bf55-7e7982e7ec97">

**Comment by ThapaVinay** [comment]
i want to work on this.

**Comment by aakshitaa** [comment]
> i want to work on this.

Sure

**Comment by aakshitaa** [comment]
This issue was completed by @ThapaVinay
