### ISSUE TITLE
create a drawer style menu 

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/Lost-And-Found-Mobile-App#8]
<img width="391" alt="image" src="https://github.com/upes-open/Lost-And-Found-Mobile-App/assets/103314396/732d2821-7056-4460-9fc7-27868df60970">
<img width="212" alt="image" src="https://github.com/upes-open/Lost-And-Found-Mobile-App/assets/103314396/91453c97-7dcf-4450-8660-05c0eb58243a">

It will contain- Home, Report found item, report lost item, help us find, items gallery, feedback and faq

**Comment by ThapaVinay** [comment]
i want to work on this

**Comment by aakshitaa** [comment]
> i want to work on this

sure
