### ISSUE TITLE
Items gallery page-  Select Category section

### ISSUE THREAD

**Issue by aakshitaa** [upes-open/Lost-And-Found-Mobile-App#9]
<img width="329" alt="image" src="https://github.com/upes-open/Lost-And-Found-Mobile-App/assets/103314396/32b4a843-5be5-494f-a490-629cbd052709">
<img width="209" alt="image" src="https://github.com/upes-open/Lost-And-Found-Mobile-App/assets/103314396/69423745-63a4-4303-beaa-fe5ec0444b0f">

It would be great if we can have the above transition where there will be 4 circles for the main categories and when we click on one then the sub categories will open up in the smaller circles, we will be using animated icons for the categories.

Refer to [Workflow](workflow.md) for the categories and subcategories.

**Comment by rishabh-108272** [comment]
I would like to work on this issue

**Comment by aakshitaa** [comment]
> I would like to work on this issue

sure

**Comment by ThapaVinay** [comment]
i want to work on this

**Comment by aakshitaa** [comment]
> i want to work on this

assigned

**Comment by ThapaVinay** [comment]
i want to work on this.
